CupCarbon v. U-One 4.2
----------------
name:Consigna 1
zoom:2
centerposition_la:-34.59890055058076
centerposition_lo:-58.4871768951416
map:0
display_details:true
draw_radio_links:true
draw_sensor_arrows:false
radio_links_color:0
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:true
