CupCarbon v. U-One 4.2
----------------
name:Consigna 4
zoom:2
centerposition_la:-34.59906834724033
centerposition_lo:-58.48640978336334
map:0
display_details:true
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:0
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:true
